name: Linkspector

on:
  pull_request:
    paths:
      - "README.md"

jobs:
  check-links:
    name: runner / linkspector
    permissions:
      pull-requests: write # required for posting review comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: any
          show_stats: true
