# https://github.com/lycheeverse/lychee-action
name: Check README.md links

on:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          format: markdown
          jobSummary: true
          files-from: lychee.txt
          archive: wayback
          suggest: true
          timeout: 3
          max-retries: 1
          exclude: https://www.npmjs.com/search* https://www.npmjs.com/package/@plone/*
          mode: emoji
          cookie-jar: cookie_jar
